### ISSUE TITLE
Assertion generated at shapeit4: src/phaser/phaser_algorithm.cpp:50

### ISSUE THREAD

**Issue by mdkeehan** [odelaneau/shapeit4#1]
Hi,

Thanks for writing such a good tool and making it MIT licensed.
We have been evaluating shapeit4 on low density cattle snp chip data and a colleague has been generating the following assertion.
``` 
shapeit4: src/phaser/phaser_algorithm.cpp:50: void phaser::phaseWindow(int, int): Assertion `threadData[id_worker].Kvec[w].size()>0' failed.
Aborted (core dumped)
```
The command line we have been using is
```
shapeit4 --really.simple.ped.phased.vcf.gz --map  1cmMb.map -O  out.vcf -R Chr5 --thread 4  -W 20000000 --effective-size 400  --pbwt-disable-init --mcmc-iterations  6b,1p,2b,1p,2b,20m
```
The input vcf has 1935 markers ranging over Chr5 which (in cattle) is 121 MB long.
So with `-W` 20,000,000 we have 6 windows with 400 markers per window.

By experimenting with the parameters I have found setting `-W` to 200,000,000 i.e force 1 window over the chromosome the command completes.

Is there a recommended minimum number of markers per window?

**Comment by odelaneau** [comment]
Looking at the assert, it's definitely related to the low density of variants. But It's a tricky problem to solve with few info. I am happy to look at this in more details if you could send me a small example dataset repoducing the error.

Cheers,

**Comment by mdkeehan** [comment]
Hi Olivier,

Thanks for responding.
It will be difficult for me to release a public dataset plus given that we have a work around
i.e. to use longer windows I won’t be following this up furthur.
Please mark the bug as closed.

Mike
