### ISSUE TITLE
Semicolon missing in phaser_algorithm.cpp

### ISSUE THREAD

**Issue by samfux84** [odelaneau/shapeit4#18]
Hi,

I tried to install the shapeit4 release 4.1.2 and would like to report some tiny issues that one needs to fix to get the software compiled.

In src/phaser/phaser_algorithm.cpp, there is a semicolon missing at the end of line 51, which causes the error:

src/phaser/phaser_algorithm.cpp: In member function ‘void phaser::phaseWindow(int, int)’:
src/phaser/phaser_algorithm.cpp:52:3: error: expected ‘;’ before ‘}’ token

Another small thing:

I had to replace all calls to isnan() by std::isnan() to avoid the error message

call of overloaded ‘isnan(double&)’ is ambiguous

Best regards

Sam

**Comment by odelaneau** [comment]
Thanks for this. I think it's fixed now.

**Comment by samfux84** [comment]
Thank you for fixing this.
