### ISSUE TITLE
shapeit4 drops all format fields

### ISSUE THREAD

**Issue by freeseek** [odelaneau/shapeit4#2]
Would it be possible for shapeit4 to avoid dropping variants that were not used for phasing and format fields originally present in the VCF file?

Furthermore, shapeit4 imputes missing genotypes. This seems okay for most applications, but when you have to rely on high quality genotypes for some delicate analyses, this can have unintended consequences. It would be nice to have an option to avoid imputing missing genotypes.

More in general, it would be nice if shapeit4 could just output VCF files equal in all aspects to the original VCF file with the only difference being that the genotypes have changed. This would go a long way guaranteeing that users with diverse applications in mind would not have to go through the additional laborious steps of importing the GT information back into the original VCF. This would be much more in line with the HTSlib/BCFtools philosophy.

**Comment by odelaneau** [comment]
I understand your concern. I've got to look at it. I guess the best and easiest solution would be to develop a small independent tool based on HTSlib that updates the original VCF using the phased data produce by shapeit4. The design of S4 does not easily allow for this.

**Comment by freeseek** [comment]
I did not realize that you can easily import back genotypes in the original VCF using `bcftools annotate` as follows:
```
bcftools annotate -Ob -o phased.input.bcf -a shapeit4.output.bcf -c FMT/GT input.bcf
```
However, the only problem remaining here is that there is no option like Eagle's `--noImpMissing` to avoid imputing missing genotypes. The information about which genotypes are missing gets just lost.

**Comment by freeseek** [comment]
I spoke too soon. Actually BCFtools does have an infrastructure to handle this although as of today it is buggy. I reference the raised [issue](https://github.com/samtools/bcftools/issues/1259) in case other users are interested in the same functionality.
