### ISSUE TITLE
Error: Illegal instruction (core dumped) 

### ISSUE THREAD

**Issue by pauline-ng** [odelaneau/shapeit4#28]
Hi,

I'm trying to install shapeit4. I follow the instructions and it seems to compile successfully. But when I run
`./shapeit4`
I get
`Illegal instruction (core dumped)`

Below is some output I get from compiling. There are no obvious errors:

`g++ -std=c++11 -O3 -mavx2 -mfma  -c src/containers/genotype_set.cpp -o obj/genotype_set.o -Isrc -I/usr/local/include -I/usr/include
g++ -std=c++11 -O3 -mavx2 -mfma  -c src/containers/haplotype_set.cpp -o obj/haplotype_set.o -Isrc -I/usr/local/include -I/usr/include
g++ -std=c++11 -O3 -mavx2 -mfma  -c src/io/graph_writer.cpp -o obj/graph_writer.o -Isrc -I/usr/local/include -I/usr/include
g++ -std=c++11 -O3 -mavx2 -mfma  -c src/io/genotype_reader1.cpp -o obj/genotype_reader1.o -Isrc -I/usr/local/include -I/usr/include
g++ -std=c++11 -O3 -mavx2 -mfma  -c src/io/genotype_reader2.cpp -o obj/genotype_reader2.o -Isrc -I/usr/local/include -I/usr/include
g++ -std=c++11 -O3 -mavx2 -mfma  -c src/io/haplotype_writer.cpp -o obj/haplotype_writer.o -Isrc -I/usr/local/include -I/usr/include
src/io/haplotype_writer.cpp: In member function 'void haplotype_writer::writeHaplotypes(std::string)':
src/io/haplotype_writer.cpp:57:15: warning: ignoring return value of 'int bcf_hdr_write(htsFile*, bcf_hdr_t*)', declared with attribute warn_unused_result [-Wunused-result]
   57 |  bcf_hdr_write(fp, hdr);
      |  ~~~~~~~~~~~~~^~~~~~~~~
g++ -std=c++11 -O3 -mavx2 -mfma  -c src/io/gmap_reader.cpp -o obj/gmap_reader.o -Isrc -I/usr/local/include -I/usr/include
g++ -std=c++11 -O3 obj/compute_job.o obj/genotype_sweep.o obj/genotype_mask.o obj/genotype_prune.o obj/genotype_build.o obj/genotype_managment.o obj/hmm_parameters.o obj/variant.o obj/haplotype_segment_double.o obj/haplotype_segment_single.o obj/main.o obj/phaser_finalise.o obj/phaser_initialise.o obj/phaser_parameters.o obj/phaser_algorithm.o obj/phaser_management.o obj/pbwt_solver.o obj/builder.o obj/variant_map.o obj/genotype_set.o obj/haplotype_set.o obj/graph_writer.o obj/genotype_reader1.o obj/genotype_reader2.o obj/haplotype_writer.o obj/gmap_reader.o /usr/local/lib/libhts.a /usr/lib/x86_64-linux-gnu/libboost_iostreams.a /usr/lib/x86_64-linux-gnu/libboost_program_options.a -o bin/shapeit4 -lz -lbz2 -lm -lpthread -llzma
`

Thanks,
Pauline

**Comment by pauline-ng** [comment]
I think it works now.

**Comment by hsiehph** [comment]
> I think it works now.
Hi Pauline,

I went into the same situation and wonder if you can share how you resolved the issue. Thanks!

Benson

**Comment by pauline-ng** [comment]
Hi Benson,

It's been so long ago I've forgotten. Maybe it was something easy like forgetting to pass the arguments in.

Best
Pauline

**Comment by hsiehph** [comment]
Thanks, Pauline. I figured out the problem was due to not all cores on our cluster have the AVX2 instruction set.

**Comment by LouisLeNezet** [comment]
Thanks a lot for your answer. I was concern by the same issue on shapeit5 !
For other people coming here:
If you are on slurm you need to add a constraint to the node to be sure to have `avx2` available.
For that you need to add to srun or sbatch:
`--constraint=avx2`
You can also check the info about your nodes with:
`scontrol show node`
