### ISSUE TITLE
ERROR: Parsing line 0 : incorrect number of columns,

### ISSUE THREAD

**Issue by NTNguyen13** [odelaneau/shapeit4#32]
Hi, I'm trying out SHAPEIT4 on my population vcf. My file is gzipped, and aligned to GRCh38. I want to use shapeit4 to impute the missing genotype and phase the genotypes.

My full command is:

`shapeit4 --input $chr_file --map /home/nguyen/Exec/shapeit4/maps/genetic_maps.b38.tar.gz  --output /mnt/Data/DGV4VN_Data/VCF_pop/DGV4VN.$chr.phased.vcf.gz  --thread 14 --region  $chr --sequencing
`
However, it ended with the error (with full log):
```

SHAPEIT
  * Author        : Olivier DELANEAU, University of Lausanne
  * Contact       : olivier.delaneau@gmail.com
  * Version       : 4.1.3
  * Run date      : 22/08/2020 - 11:34:54

Files:
  * Input VCF     : [testMASH_504.chr3.vep.norm.vqsr.vcf.gz]
  * Genetic Map   : [/home/nguyen/Exec/shapeit4/maps/genetic_maps.b38.tar.gz]
  * Output VCF    : [/mnt/Data/DGV4VN_Data/VCF_pop/DGV4VN.chr3.phased.vcf.gz]

Parameters:
  * Seed    : 15052011
  * Threads : 14 threads
  * MCMC    : 15 iterations [5b + 1p + 1b + 1p + 1b + 1p + 5m]
  * PBWT    : Depth of PBWT neighbours to condition on: 4
  * PBWT    : Store indexes at variants [MAC>=2 / MDR<=0.5 / Dist=0.0005 cM]
  * HMM     : K is variable / min W is 2.50cM / Ne is 15000
  * HMM     : Recombination rates given by genetic map
  * HMM     : AVX2 optimization active
  * IBD2    : length>=3.00cM [N>=10000 / MAF>=0.000 / MDR<=0.500]

Initialization:
[W::hts_idx_load2] The index file is older than the data file: testMASH_504.chr3.vep.norm.vqsr.vcf.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: testMASH_504.chr3.vep.norm.vqsr.vcf.gz.tbi
  * VCF/BCF scanning [N=504 / L=1870919 / Reg=chr3] (362.66s)
[W::hts_idx_load2] The index file is older than the data file: testMASH_504.chr3.vep.norm.vqsr.vcf.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: testMASH_504.chr3.vep.norm.vqsr.vcf.gz.tbi
  * VCF/BCF parsing [Hom=84.7% / Het=9.1% / Mis=6.3%] (365.12s)

ERROR: Parsing line 0 : incorrect number of columns, observed: 1 expected: 3
```

What have gone wrong in my case? Thank you.

**Comment by yuantiaotiao** [comment]
Hello, I also encountered this problem, may I ask you how to solve it

**Comment by yuantiaotiao** [comment]
> Hi, I'm trying out SHAPEIT4 on my population vcf. My file is gzipped, and aligned to GRCh38. I want to use shapeit4 to impute the missing genotype and phase the genotypes.
> 
> My full command is:
> 
> `shapeit4 --input $chr_file --map /home/nguyen/Exec/shapeit4/maps/genetic_maps.b38.tar.gz --output /mnt/Data/DGV4VN_Data/VCF_pop/DGV4VN.$chr.phased.vcf.gz --thread 14 --region $chr --sequencing ` However, it ended with the error (with full log):
> 
> ```
> 
> SHAPEIT
>   * Author        : Olivier DELANEAU, University of Lausanne
>   * Contact       : olivier.delaneau@gmail.com
>   * Version       : 4.1.3
>   * Run date      : 22/08/2020 - 11:34:54
> 
> Files:
>   * Input VCF     : [testMASH_504.chr3.vep.norm.vqsr.vcf.gz]
>   * Genetic Map   : [/home/nguyen/Exec/shapeit4/maps/genetic_maps.b38.tar.gz]
>   * Output VCF    : [/mnt/Data/DGV4VN_Data/VCF_pop/DGV4VN.chr3.phased.vcf.gz]
> 
> Parameters:
>   * Seed    : 15052011
>   * Threads : 14 threads
>   * MCMC    : 15 iterations [5b + 1p + 1b + 1p + 1b + 1p + 5m]
>   * PBWT    : Depth of PBWT neighbours to condition on: 4
>   * PBWT    : Store indexes at variants [MAC>=2 / MDR<=0.5 / Dist=0.0005 cM]
>   * HMM     : K is variable / min W is 2.50cM / Ne is 15000
>   * HMM     : Recombination rates given by genetic map
>   * HMM     : AVX2 optimization active
>   * IBD2    : length>=3.00cM [N>=10000 / MAF>=0.000 / MDR<=0.500]
> 
> Initialization:
> [W::hts_idx_load2] The index file is older than the data file: testMASH_504.chr3.vep.norm.vqsr.vcf.gz.tbi
> [W::hts_idx_load2] The index file is older than the data file: testMASH_504.chr3.vep.norm.vqsr.vcf.gz.tbi
>   * VCF/BCF scanning [N=504 / L=1870919 / Reg=chr3] (362.66s)
> [W::hts_idx_load2] The index file is older than the data file: testMASH_504.chr3.vep.norm.vqsr.vcf.gz.tbi
> [W::hts_idx_load2] The index file is older than the data file: testMASH_504.chr3.vep.norm.vqsr.vcf.gz.tbi
>   * VCF/BCF parsing [Hom=84.7% / Het=9.1% / Mis=6.3%] (365.12s)
> 
> ERROR: Parsing line 0 : incorrect number of columns, observed: 1 expected: 3
> ```
> 
> What have gone wrong in my case? Thank you.

Hello, I also encountered this problem, may I ask you how to solve it
