### ISSUE TITLE
missing genotypes in scaffold

### ISSUE THREAD

**Issue by 23andme-jaredo** [odelaneau/shapeit4#40]
Are missing genotypes allowed in the scaffolds?

For example:

```
0|1 ./.
./. 0|1
```

The use case is samples coming from different microarrays.

thanks!

Jared

**Comment by odelaneau** [comment]
Hey Jared,

I hope you're okay!

S4 only considers genotypes in the scaffold (--scaffold) that are:
   (i) phased (i.e. "|"),
   (ii) heterozygous,
   (iii) consistent with input data (--input).

All genotypes that do not pass (i) to (iii) are simply ignored. It doesn't matter if the scaffold retained from one sample to the other massively differs.

Best

**Comment by 23andme-jaredo** [comment]
That's great. Thanks.
