### ISSUE TITLE
About including PS (phase set) information

### ISSUE THREAD

**Issue by SIJAE-WOO** [odelaneau/shapeit4#42]
Hi, I ran shapeit4 using '--use-PS' option.  But, PS (phase set) information was not included in the output file of shapeit4.
![image](https://user-images.githubusercontent.com/59044899/102289859-07428e00-3f83-11eb-8706-18421234c03f.png)

I want to check GT (genotype) with PS (phase set), simultaneously.
If you have a solution, please let me know.
Otherwise, is there only one phase set in the output file (in other words, all phased variants are in the same phase set)?

Bests,

Sijae

**Comment by odelaneau** [comment]
Dear Sijae,

After a S4 run base don --use-PS, all variants are in the same PS, so no need to specify it in the output.

Best,

Olivier

**Comment by SIJAE-WOO** [comment]
I got it. Thank you very much!

Sijae
