### ISSUE TITLE
'--pbwt-disable-init' not recognized

### ISSUE THREAD

**Issue by mvaudel** [odelaneau/shapeit4#46]
Hi,

When running using the '--pbwt-disable-init' option, I get `Error parsing command line arguments: unrecognised option '--pbwt-disable-init'`. Am I doing something wrong?

Thanks for developing and supporting this great resource.

Marc

**Comment by odelaneau** [comment]
Dear Marc,

My bad, I removed this option by mistake. It's now back.

Best,

Olivier.

**Comment by mvaudel** [comment]
Fantastic, thanks for fixing this so quickly!

Marc
