### ISSUE TITLE
ERROR: Parsing line 0 : incorrect number of columns, observed: 1 expected: 3

### ISSUE THREAD

**Issue by jessicahr** [odelaneau/shapeit4#50]
I'm trying to run Shapeit4 with some files and I obtain en Error 
(ERROR: Parsing line 0 : incorrect number of columns, observed: 4 expected: 3).
I even tried with the unphased file in /test and I have the same error.

This is how I used it (same with .vcf):
shapeit4 --input unphased.bcf --map ../maps/genetic_maps.b37.tar.gz --region 20 --output test-phased.bcf

This is the log, I don't obtain an output file:
<<
SHAPEIT
  * Author        : Olivier DELANEAU, University of Lausanne
  * Contact       : olivier.delaneau@gmail.com
  * Version       : 4.1.2
  * Run date      : 11/03/2021 - 13:25:50

Files:
  * Input VCF     : [unphased.bcf]
  * Genetic Map   : [../maps/genetic_maps.b37.tar.gz]
  * Output VCF    : [test-phased.bcf]

Parameters:
  * Seed    : 15052011
  * Threads : 1 threads
  * MCMC    : 15 iterations [5b + 1p + 1b + 1p + 1b + 1p + 5m]
  * PBWT    : Depth of PBWT neighbours to condition on: 4
  * PBWT    : Store indexes at variants [MAC>=2 / MDR<=0.5 / Dist=0.02 cM]
  * HMM     : K is variable / min W is 2.50cM / Ne is 15000
  * HMM     : Recombination rates given by genetic map
  * HMM     : !AVX2 optimization inactive!
  * IBD2    : length>=3.00cM [N>=150 / MAF>=0.010 / MDR<=0.500]

Initialization:
  * VCF/BCF scanning [N=203 / L=24990 / Reg=20] (0.01s)
  * VCF/BCF parsing [Hom=90.0% / Het=10.0% / Mis=0.0%] (0.08s)

ERROR: Parsing line 0 : incorrect number of columns, observed: 4 expected: 3
>>

Does anyone had the same problem??
Thank you so much!

**Comment by odelaneau** [comment]
Untar genetic_maps.b37.tar.gz first and then specify the file matching your chr with --map.

Cheers,

**Comment by jessicahr** [comment]
That was the problem! Thank you so much!
